version: '3.7'

services:
 amrillajev-docker:
  image: amrillajev-docker:dev
  container_name: amrillajev-docker
  build:
   context: ./docker
   target: amrillajev-docker
   dockerfile: ./Dockerfile.dev
  ports:
   - "85:80" # HOST_PORT:CONTAINER_PORT
   - "448:443"
   # network_mode: "host" # sdileni localhost s hostem, pozor na konflikt portu, viz. apache.ports.conf a apache.vhost.conf, nefunguje na ios
  volumes:
   - .:/var/www
   - ./docker/php.ini:/usr/local/etc/php/php.ini
   - ./log:/var/log/parkovani:rw
   - ./docker/apache.ports.conf:/etc/apache2/ports.conf
   - ./docker/apache.vhost.conf:/etc/apache2/sites-enabled/vhost.conf
 mysqldb:
  image: mariadb:latest
  volumes:
    - ./data/database:/var/lib/mysql:rw
    - ./docker/mysql/mariadb.cnf:/etc/mysql/mariadb.cnf
    - ./db-dump/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
  ports:
    - 3307:3306
  environment:
    - MYSQL_ROOT_PASSWORD=root
    - MYSQL_DATABASE=db_name
    - MYSQL_USER=user
    - MYSQL_PASSWORD=root
    # command: --init-file /docker-entrypoint-initdb.d/init.sql
